### ISSUE TITLE
[feature request] - Add env variable substitution

### ISSUE THREAD

**Issue by CalvinWilkinson** [denoland/deno_task_shell#115]
Hello!!

I thought it would be really nice to support _**env variable substitution**_ in the deno task values in the _**deno.json**_.

This is currently done inside of VSCode for _**launch**_ and _**task**_ configs.

Here is an example of what I am doing in my launch configs in the _**launch.json**_ file:
```json
{
	"request": "launch",
	"name": "Run",
	"type": "node",
	"program": "${workspaceFolder}/playground.ts",
	"cwd": "${workspaceFolder}",
	"env": {
		"EA_CICD_TOKEN": "${env:EA_CICD_TOKEN}", 👈🏻 This here would be nice to add to deno tasks
	},
	"runtimeArgs": [
		"run",
		"-A",
		"--inspect-wait"
	],
        "runtimeExecutable": "${userHome}\\.deno\\bin\\deno.exe",
	"attachSimplePort": 9229,
},
```

So in the `deno.json` file, we could do this:
```json
{
    "tasks": {
        "run-my-file": "deno run -A ./my-file.ts ${env:ACCESS_TOKEN}" 👈🏻 This could be an environment var in the OS operating system
    },
}
```

Maybe there is a way to do this, but I could not find out how.  If so, please don't hesitate to let me know.  

Thanks!!

**Comment by dsherret** [comment]
If I understand correctly, this is already possible:

```json
{
    "tasks": {
        "run-my-file": "deno run -A ./my-file.ts $ACCESS_TOKEN"
    }
}
```

**Comment by CalvinWilkinson** [comment]
I swear I tried that as well, but I must not have realized I had something typed wrong. 

But it works!!  Thank you!!  Greatly appreciate it!!
