### ISSUE TITLE
Running task with argument will enclose it in quotes

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno_task_shell#34]
```
deno task node:test test-http-upgrade-agent.js
Warning deno task is unstable and may drastically change in the future
Task node:test deno test --unstable --allow-all node/_tools/test.ts "test-http-upgrade-agent.js"
error: No such file or directory (os error 2)
```

**Comment by dsherret** [comment]
Yeah that's by design at the moment so that we didn't have to implement extra logic for determining if we need to surround an argument in quotes or note. Is it causing issues?

**Comment by bartlomieju** [comment]
> Yeah that's by design at the moment so that we didn't have to implement extra logic for determining if we need to surround an argument in quotes or not. Is it causing issues?

Yes, in `deno_std` this causes everything to try and run a file that contains quotes - ie. these are passed verbatim to the code, instead of being stripped of quotes before being put in `Deno.args`

**Comment by dsherret** [comment]
`deno test` has a usage like:

```
deno test [OPTIONS] [files]...
```

So it can't find "test-http-upgrade-agent.js" in the root. Talking with Bartek, it looks like there is a bug where it doesn't forward `--` in deno task.

**Comment by dsherret** [comment]
Opened https://github.com/denoland/deno/pull/14419 which will fix the root cause here of a double hyphen not being forward to deno task.

The quoted args is done in the CLI and should have no effect to my knowledge.
