### ISSUE TITLE
Ability to execute tasks by injecting Deno args

### ISSUE THREAD

**Issue by fkdiomande** [denoland/deno_task_shell#49]
Task definition by injecting `${Deno.args[0]}`:

```
{
  "tasks": {
    "test:watch": "deno test --watch -A --unstable ${Deno.args[0]}"
  }
}
```

and run task:

`deno task test:watch MyDirectory`

**Comment by bartlomieju** [comment]
You can achieve this by doing `deno task test:watch -- MyDirectory`

**Comment by fkdiomande** [comment]
This `deno task test:watch -- MyDirectory` does not works. But I succeeded with `deno task test:watch MyDirectory`

Thanks
