### ISSUE TITLE
Support glob expansion

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_task_shell#6]
- globstar
- ~~nullglob? Maybe yes?~~ error on no matches

**Comment by LeoDog896** [comment]
So what should we base the globbing settings on then? In order to implement this, we need to know what we're going for.

**Comment by mechanoid** [comment]
Hi there! 👋 Is there anything planned for this in the  near future?

**Comment by LeoDog896** [comment]
Alright! All any contributor here needs is the specific glob format. Would nullglob work fine for that? If so, I'm perfectly fine with PRing this.

**Comment by bartlomieju** [comment]
@dsherret thoughts?

**Comment by dsherret** [comment]
I think instead of nullglob maybe we can have the command error when nothing matches? From https://unix.stackexchange.com/questions/204803/why-is-nullglob-not-default

> A more sensible default, and the one of csh, tcsh, zsh or fish 2.3+ (and of early Unix shells) is to cancel the command altogether if the glob doesn't match.

That still gives people the option to fallback to another command on failure.

----

For implementing this I think we _shouldn't_ implement this behaviour in the shell yet. Instead we should start by implementing parsing in https://github.com/denoland/deno_task_shell/blob/main/src/parser.rs , which can be done gradually. I don't think we should use a separate crate for implementing this feature so that we have full control over how it works.

To start, essentially parsing would pass for shell expansion, but then it would error when executing in the shell. Then afterwards in a separate PR we can implement this in the shell.

**Comment by bartlomieju** [comment]
@LeoDog896 is it something you're still interested in opening a PR for?

**Comment by dsherret** [comment]
I'm just realizing that we wouldn't need to use parsing for this and it should be done entirely in the shell. I'm about half way done implementing it and should open a PR soon.
