### ISSUE TITLE
Support redirection with pipeline

### ISSUE THREAD

**Issue by PkmX** [denoland/deno_task_shell#64]
```json
{
  "tasks": {
    "test": "echo 1 | sed -e 's/1/2/' > output.txt"
  }
}
```

This doesn't redirect the stdout of `sed` command to `output.txt`, which is unexpected from normal shell behavior:

```sh
$ deno task test
Task test echo 1 | sed -e 's/1/2/' > output.txt
2
$ cat output.txt
cat: output.txt: No such file or directory

$ echo 1 | sed -e 's/1/2/' > output.txt
$ cat output.txt
2
```

**Comment by dsherret** [comment]
This is both a bug and an enhancement. Bug is that there wasn't an error shown for this not being supported... enhancement is supporting it. Opened #65.
