### ISSUE TITLE
Watch in task commands

### ISSUE THREAD

**Issue by amundo** [denoland/deno_task_shell#76]
It would be helpful to have a `watch` command in deno `task`, e.g.:

```json
{
  "task": {
      "build": "watch deno build-html.js"
  }
}
```

Not sure if I got the syntax right, but the idea would be the command would run whenever `build-html.js` changes.

**Comment by niedzielski** [comment]
I love the idea of this but how would you know what the dependencies are in a generic way?

**Comment by amundo** [comment]
Hmm that’s a good point, perhaps it’s not possible.
