### ISSUE TITLE
Consider relying on uutils/coreutils

### ISSUE THREAD

**Issue by Hofer-Julian** [denoland/deno_task_shell#94]
At the moment, `deno_task_shell` reimplements commands from coreutils.
Therefore, I can imagine, that it's relatively easy to hit a case where these commands behave unexpectedly.
An alternative would be to rely on [uutils/coreutils](https://github.com/uutils/coreutils) instead.
They aim to be a drop-in replacement for the GNU utils. Nushell is already starting to port to uutils, you can read their story here: https://www.nushell.sh/blog/2023-09-05-why-uu.html.

Here is the PR where uutils/coreutil's cp command was added to nushell: https://github.com/nushell/nushell/pull/10097

**Comment by dsherret** [comment]
See https://github.com/denoland/deno_task_shell/issues/32#issuecomment-1101698173

**Comment by Hofer-Julian** [comment]
Oh sorry, seems like I have missed this issue :)
