### ISSUE TITLE
Deno task `cp` wildcard does not work correctly

### ISSUE THREAD

**Issue by Mqxx** [denoland/deno_task_shell#95]
Hey,

I want to recursively copy all `.html` files from `./src/client/` to `./dist/`. For this I wanted to use the following task command:

```
cp -r ./src/client/**/*.html ./dist/
```

This command should normally (in my opinion) copy all files ending with `.html` recursively to `./dist/`. However, only the first file ending with `.html` is copied to `./dist/`.

Is this how it is meant to be?

<br>

**Short summary**

- **Command used:**
```
cp -r ./src/client/**/*.html ./dist/
```

- **Expected behavior:**
All files ending with `.html` and located in `.src/client/` are copied to `./dist/` with the same folder structure.

> [Deno Glob Expansion Reference](https://docs.deno.com/runtime/manual/tools/task_runner#glob-expansion)
> ```
> # match .ts files in the current and descendant directories
> echo **/*.ts
> ```

- **Actual behavior:**
Only the file which ends with `.html` and is in the first directory level will be copied to `./dist/`.

**Comment by dsherret** [comment]
This seems to be the behaviour I see on linux:

```shellsession
# turn on globstar
$ shopt -s globstar
```

```shellsession
$ echo src/client/**/*.html
src/client/other/test2.html src/client/test.html
$ cp -r ./src/client/**/*.html ./dist/
$ echo **/*.html
dist/test.html dist/test2.html src/client/other/test2.html src/client/test.html
```

Now if I execute the following:

```
$ rm dist/test.html dist/test2.html
$ echo **/*.html
src/client/other/test2.html src/client/test.html
$ deno task copy
Task copy cp -r ./src/client/**/*.html ./dist/
$ echo **/*.html
dist/test.html dist/test2.html src/client/other/test2.html src/client/test.html
```

So it seems to be working as expected?

**Comment by Mqxx** [comment]
Okay thanks for checking. Is there a command for the thing that I want to achieve?

**Comment by Mqxx** [comment]
Is there some way of using `xargs` to solve this?

**Comment by Mqxx** [comment]
I have found a solution to just copy my html files. Since I use ESBuild in my project anyway, I can also use the build-in `copy loader` of ESBuild:

```
deno run -A https://deno.land/x/esbuild@v0.19.4/mod.js --loader:.html=copy --outdir=dist/ ./**/index.html
```
