### ISSUE TITLE
deno_task_shell doesn’t handle escaping of parentheses `(` and `)`

### ISSUE THREAD

**Issue by luangong** [denoland/deno_task_shell#97]
I was trying to use the [dax](https://deno.land/x/dax) module (which internally uses [deno_task_shell](https://github.com/denoland/deno_task_shell)) to call some ImageMagick commands but encountered an issue when the command contains escaped parentheses.

FYI: dax is a cross platform shell tools for Deno inspired by [zx](https://github.com/google/zx). dax uses [deno_task_shell](https://github.com/denoland/deno_task_shell) internally to parse commands.

Some usage of ImageMagick requires using parentheses (`(` and `)`) as command line arguments so they’re usually escaped, like in [this example](https://www.imagemagick.org/Usage/basics/#parenthesis):

```bash
magick eye.gif \( storm.gif -negate \) +append cmd_bracket.gif
```

They have nothing to do with subshells, but dax (and thus deno_task_shell) fails to parse commands containing raw and escaped parentheses. The following Deno tasks also demonstrates this issue:

```json
{
  "tasks": {
    "paren": "echo ( foo bar )",
    "paren2": "echo \\( foo bar \\)"
  }
}
```

```bash
$ deno task paren
Task paren echo ( foo bar )
error: Error parsing script 'paren'.

Caused by:
    Unexpected character.
      ( foo bar )
      ~
```

```bash
$ deno task paren2
Task paren2 echo \( foo bar \)
error: Error parsing script 'paren2'.

Caused by:
    Unexpected character.
      ( foo bar \)
      ~
```

The workaround I found is to enclose the parentheses with single- or double-quotes, like this:

```json
{
  "tasks": {
    "paren": "echo '(' foo bar ')'"
  }
}
```

```bash
$ deno task paren
Task paren echo '(' foo bar ')'
( foo bar )
```

Question: Is it by design or a bug?

**Comment by andrewbrey** [comment]
> FYI: dax is a cross platform shell tools for Deno inspired by [zx](https://github.com/google/zx). dax uses [deno_task_shell](https://github.com/denoland/deno_task_shell) internally to parse commands.

@luangong I'm just a fly on the wall, and had to stop and say that this issue made me chuckle because `dax` is written and maintained by @dsherret, the original & main contributor to `deno_task_shell` (he's also a core contributor to Deno plus he wrote `dprint` and some other super cool stuff too) :smile:
